# -*- coding: utf-8 -*-
"""Analisis Sentimen User PLN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRx6zajHHekFpPzYBpSkMOpuVG1hs8Wb
"""

import pandas as pd
import gdown
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter
import matplotlib.ticker as mtick
import matplotlib.cm as cm
import seaborn as sns
import numpy as np
import plotly.express as px
import matplotlib.dates as mdates
import re
from sklearn.feature_extraction.text import CountVectorizer
from textblob import TextBlob

import warnings
warnings.filterwarnings('ignore')

"""##Scraping Data"""

!pip install google-play-scraper

from google_play_scraper import reviews, Sort

result, continuation_token = reviews(
    'com.icon.pln123',  # Ganti dengan package name aplikasi
    lang='id',          # Bahasa ulasan
    country='id',       # Negara pengguna
    sort=Sort.NEWEST,   # Sortir ulasan
    count=500           # Jumlah ulasan yang diambil
)

data = [{
    'userName': r['userName'],
    'score': r['score'],
    'datetime': r['at'].strftime('%Y-%m-%d %H:%M:%S'),
    'reviewText': r['content']
} for r in result]

# Buat DataFrame
df = pd.DataFrame(data)

df.head()

df.info()

"""## Data Preprocessing

####**Data Transformation**
"""

# ganti tipe data
df['datetime'] = pd.to_datetime(df['datetime'])
df.info()

"""####**Duplicate checking**"""

# Cek duplikasi by nama dan email
duplicate_rows = df[df.duplicated(subset=['userName', 'reviewText'], keep=False)]
print(f"jumlah duplikasi : {len(duplicate_rows)}")
df.drop_duplicates(subset=['userName', 'reviewText'],keep='first', inplace=True)

"""####**Null Values checking**"""

# Cek null values
df.isnull().sum()

df.shape

df.head(5)

"""# Wordcloud Preprocessing"""

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

# Mengisi nilai NaN dengan string kosong ('')
df['reviewText'] = df['reviewText'].fillna(" ")

# Menggabungkan teks dari kolom 'Review text'
text=' '.join(df['reviewText'].astype(str).tolist())

stopwords = set(STOPWORDS)

wc = WordCloud(stopwords=stopwords, background_color="black", max_words=500, width=800, height=400)

wc.generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wc, interpolation='bilinear')
plt. axis("off")
plt. show()

"""### Word Frequent Checking"""

import matplotlib.pyplot as plt
from collections import Counter

text = "".join(df["reviewText"])

tokens = text.split()
word_counts = Counter(tokens)

top_words = word_counts.most_common(10)

word, count = zip(*top_words)

# palet warna
colors = plt.cm.tab10(range(len(word)))

plt.figure(figsize=(12, 6))
bars = plt.bar(word, count, color=colors)
plt.xlabel("Kata-Kata Sering Muncul", fontsize=12, fontweight='bold')
plt.ylabel("Jumlah Kata", fontsize=12, fontweight='bold')
plt.title("Frekuensi Kata", fontsize=18, fontweight='bold')
plt.xticks(rotation=45)

# Menambahkan angka rata tengah di atas setiap bar
for bar, num in zip(bars, count):
    plt.text(bar.get_x() + bar.get_width() / 2 - 0.1, num + 1, str(num), fontsize=12, color='black', ha='center')

plt.show()

"""### Cleaning"""

import re
import string
import nltk

# Fungsi untuk menghapus emoji
! pip install emoji
import emoji

def remove_emoji(text):
    if text is not None and isinstance(text, str):
        return emoji.replace_emoji(text, replace='')
    return text

# Fungsi untuk menghapus simbol
def remove_symbols(text):
    if text is not None and isinstance(text, str):
        text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

# Fungsi untuk menghapus angka
def remove_numbers(text):
    if text is not None and isinstance(text, str):
        text = re.sub(r'\d+', '', text)
    return text

# Fungsi untuk menambahkan spasi setelah koma
def add_space_after_comma(text):
    if text is not None and isinstance(text, str):
        return re.sub(r',(?=\S)', ', ', text)
    return text

df['Cleaning'] = df['reviewText'].apply(lambda x: add_space_after_comma(x))
df['Cleaning'] = df['Cleaning'].apply(lambda x: remove_emoji(x))
df['Cleaning'] = df['Cleaning'].apply(lambda x: remove_symbols(x))
df['Cleaning'] = df['Cleaning'].apply(lambda x: remove_numbers(x))

df.head(10)

"""### Case Folding"""

def case_folding(text):
    if isinstance(text, str):
        lowercase_text = text.lower()
        return lowercase_text
    else:
        return text

df['case_folding'] = df['Cleaning'].apply(case_folding)
df

"""### World Normalization"""

import pandas as pd

# fungsi penggantian kata tidak baku
def replace_taboo_words (text, kamus_tidak_baku):
    if isinstance(text, str):
        words = text.split()
        replaced_words = []
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []

        for word in words:
            if word in kamus_tidak_baku:
                baku_word = kamus_tidak_baku[word]
                if isinstance(baku_word, str) and all(char.isalpha() for char in baku_word):
                    replaced_words.append(baku_word)
                    kalimat_baku.append(baku_word)
                    kata_diganti.append(word)
                    kata_tidak_baku_hash.append(hash (word))
                # else:
                #   replaced_words.append('<karakter eksplisit"।
                #   kalimat_baku.append(word)
            else:
                replaced_words.append(word)
        # Corrected indentation here
        replaced_text = ' '.join(replaced_words)
    else:
        replaced_text = ''
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []
    # Corrected indentation here
    return replaced_text, kalimat_baku, kata_diganti, kata_tidak_baku_hash

# Membaca kamus kata tidak baku
kamus_data = pd.read_excel("kamuskatabaku.xlsx")
kamus_tidak_baku = dict(zip(kamus_data['tidak_baku'], kamus_data['kata_baku']))

#Menerapkan Fungsi Penggantian Kata Tidak Baku
df['normalisasi'], df['Kata_Baku'], df['Kata_Tidak_Baku'], df['Kata_Tidak_Baku_Hash'] = zip(
    *df['case_folding'].apply(lambda x: replace_taboo_words(x, kamus_tidak_baku))
)
df = pd.DataFrame(df[['datetime', 'userName', 'score', 'reviewText', 'Cleaning', 'case_folding', 'normalisasi']])

df

"""# Text Preprocessing

## Tokenization
"""

def tokenize (text) :
  tokens = text.split()
  return tokens

df['tokenize'] = df['normalisasi'].apply(lambda x: tokenize(x))

df_cleaned = df[['datetime', 'userName', 'score', 'normalisasi', 'tokenize']].rename(columns={'normalisasi':'reviewText_cleaned'})
df_cleaned.head()

"""## Proses Stopword Removal"""

from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('indonesian'))

def remove_stopwords(text) :
  return [word for word in text if word not in stop_words]

df_cleaned['stopword removal'] = df_cleaned['tokenize'].apply(lambda x: remove_stopwords(x))
df_cleaned

"""## Proses Steaming Data"""

!pip install Sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_text(text):
    return [stemmer.stem(word) for word in text]

df_cleaned['steming_data'] = df_cleaned['stopword removal'].apply(lambda x: ' '.join(stem_text(x))).replace('', np.nan)
df_cleaned.head(5)

df_cleaned.info()

data = df_cleaned.dropna()
data.info()

from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

# Menggabungkan teks dari kolom 'steming_data'
text = ' '.join(df_cleaned['stopword removal'].astype(str).tolist())

stopwords = set(STOPWORDS)

wc = WordCloud(stopwords=stopwords, background_color="white", max_words=500, width=800, height=400)

wc.generate(text)

plt.figure(figsize=(10, 5))
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.show()

import matplotlib.pyplot as plt
from collections import Counter
from wordcloud import STOPWORDS

# Convert the list of words in 'stopword removal' to strings before joining
text = ' '.join([' '.join(words) for words in df_cleaned["stopword removal"]])

stopwords = set(STOPWORDS)

tokens = [word for word in text.split() if word not in stopwords]
word_counts = Counter(tokens)

top_words = word_counts.most_common(10)
word, count = zip(*top_words)
# Menggunakan palet warna lebih lembut
colors = plt.cm.Pastel1(range(len(word)))

# Membuat plot
plt.figure(figsize=(12, 5))
bars = plt.bar(word, count, color=colors)
plt.xlabel("Kata-Kata Sering Muncul", fontsize=12, fontweight='bold')
plt.ylabel("Jumlah Kata", fontsize=12, fontweight='bold')
plt.title("Frekuensi Kata", fontsize=18, fontweight='bold')
plt.xticks(rotation=45)

# Menambahkan angka rata tengah di atas setiap bar
for bar, num in zip(bars, count):
    plt.text(bar.get_x() + bar.get_width() / 2 - 0.1, num + 1, str(num), fontsize=12, color='black', ha='center')

# Menampilkan plot
plt.show()

"""# Labeling

## Pelabelan Data
"""

data = pd.DataFrame(data[['score',  'steming_data']])
data.head()

data['Sentiment'] = data ['score'].apply(lambda x: 'positive' if x > 3 else ('neutral' if x == 3 else 'negative'))
data

"""## Wordcloud"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# memsisahkan dataset berdasarkan sentimen
sentimen_negative = data[data['Sentiment'] == 'negative']['steming_data'].str.cat(sep=' ')
sentimen_neutral = data[data['Sentiment'] == 'neutral']['steming_data'].str.cat(sep=' ')
sentimen_positive = data[data['Sentiment'] == 'positive']['steming_data'].str.cat(sep=' ')

# Membuat dan menampilkan wordcloud

def create_wordcloud(text, title):
    wordcloud = WordCloud(width=800, height=400, random_state=42, max_font_size=100, colormap='Reds',background_color='white').generate(text)
    return wordcloud

# membuat wordcloud untuk sentimen negatif
wordcloud_negative = create_wordcloud(sentimen_negative, 'Wordcloud Sentimen negative')

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_negative, interpolation='bilinear')
plt.axis('off')
plt.title('Wordcloud Sentimen negative')
plt.show()

# Membuat dan menampilkan wordcloud

def create_wordcloud(text, title):
    wordcloud = WordCloud(width=800, height=400, random_state=42, max_font_size=100, colormap='Blues',background_color='white').generate(text)
    return wordcloud

# membuat wordcloud untuk sentimen netral
wordcloud_neutral=create_wordcloud(sentimen_neutral, 'Wordcloud Sentimen netral')

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_neutral, interpolation='bilinear')
plt.axis('off')
plt.title('Wordcloud Sentimen neutral')
plt.show()

# Membuat dan menampilkan wordcloud

def create_wordcloud(text, title):
    wordcloud = WordCloud(width=800, height=400, random_state=42, max_font_size=100, colormap='Greens',background_color='white').generate(text)
    return wordcloud

# membuat wordcloud untuk sentimen negatif
wordcloud_positive=create_wordcloud(sentimen_positive, 'Wordcloud Sentimen positive')

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_positive, interpolation='bilinear')
plt.axis('off')
plt.title('Wordcloud Sentimen positive')
plt.show()

"""## Distribusi Sentimen"""

import plotly.express as px

# Hitung jumlah masing-masing label sentimen
sentiment_counts = data['Sentiment'].value_counts().reset_index()
sentiment_counts.columns = ['Sentiment', 'Count']

# Barplot dengan Plotly
fig = px.bar(
    sentiment_counts,
    x='Sentiment',
    y='Count',
    text='Count',
    title='Distribusi Sentimen menggunakan BERT',
    color='Sentiment',
    color_discrete_sequence=["#1dd1a1", "#ff6b6b", "#54a0ff"]
)

# Tambahkan label di atas bar
fig.update_traces(textposition='outside')
fig.update_layout(
    xaxis_title='Sentimen',
    yaxis_title='Jumlah',
    uniformtext_minsize=8,
    uniformtext_mode='hide'
)

fig.show()

"""#Modeling

## Split Data
"""

# Memisahkan data training dan testing
from sklearn.model_selection import train_test_split

# Features (text data) and target (sentiment)
X = data['steming_data']
y = data['Sentiment']

# Split data into training and testing sets
# test_size: the proportion of the dataset to include in the test split (e.g., 0.2 for 20%)
# random_state: a seed for the random number generator for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


# Create labels and values for the bar plot
labels = ['Data Training', 'Data Testing']
values = [len(X_train), len(X_test)]

# Create the bar plot
plt.figure(figsize=(6, 4)) # Adjust figure size as needed
ax = sns.barplot(x=labels, y=values, palette='viridis')

# Add title and labels
plt.title('Jumlah Data Latih dan Data Uji', fontsize=14, pad=20)
plt.xlabel('Jenis Data', fontsize=12)
plt.ylabel('Jumlah Data', fontsize=12)

# Add the count values above the bars
for i, value in enumerate(values):
    ax.text(i, value + 10, str(value), ha='center', va='bottom', fontsize=10) # Adjust vertical position (+10) as needed

# Format y-axis to show integers
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f'{int(x)}'))


plt.show()

"""##NLP"""

!pip install transformers
!pip install bertopic

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

X_train = X_train.tolist()

topic_model = BERTopic(
    language="indonesian",
    top_n_words=10,
    verbose=True
)
topics, probs = topic_model.fit_transform(X_train)
topic_model.get_topic_info()

topic_model.visualize_barchart()

# abaikan topik noise (-1) jika ada
topics = sorted([t for t in topic_model.get_topics().keys() if t != -1])

for topic in topics:
    # Mendapatkan kata-kata beserta bobotnya
    topic_words = dict(topic_model.get_topic(topic))

    # Membuat wordcloud berdasarkan frekuensi kata
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate_from_frequencies(topic_words)

    # Menampilkan wordcloud
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation="bilinear")
    plt.title(f"WordCloud untuk Topik {topic}")
    plt.axis("off")
    plt.show()

from transformers import pipeline
import pandas as pd

# 1. Buat pipeline
sentiment_classifier = pipeline(
    "sentiment-analysis",
    model="w11wo/indonesian-roberta-base-sentiment-classifier"
)

# 2. Pastikan kolom data adalah List[str]
texts = data["steming_data"].dropna().astype(str).tolist()

# 3. Jalankan batch prediksi
results = sentiment_classifier(texts, truncation=True)

# 4. Buat DataFrame hasilnya
sentiment_df = pd.DataFrame(results)

# 5. Gabungkan dengan data asli
df_bert = pd.concat([data["steming_data"].copy().reset_index(drop=True), sentiment_df], axis=1)

# 6. Lihat hasil
df_bert[["steming_data", "label", "score"]].head()

"""## Distribusi Sentimen"""

import plotly.express as px

# Hitung jumlah masing-masing label sentimen
sentiment_counts = df_bert['label'].value_counts().reset_index()
sentiment_counts.columns = ['Sentiment', 'Count']

# Barplot dengan Plotly
fig = px.bar(
    sentiment_counts,
    x='Sentiment',
    y='Count',
    text='Count',
    title='Distribusi Sentimen menggunakan BERT',
    color='Sentiment',
    color_discrete_sequence=["#1dd1a1", "#ff6b6b", "#54a0ff"]
)

# Tambahkan label di atas bar
fig.update_traces(textposition='outside')
fig.update_layout(
    xaxis_title='Sentimen',
    yaxis_title='Jumlah',
    uniformtext_minsize=8,
    uniformtext_mode='hide'
)

fig.show()

"""## evaluation model"""

from sklearn.metrics import classification_report

# Pastikan hasil prediksi label dan label asli dalam format yang sama
y_true = data['Sentiment']
y_pred = df_bert['label']

# Tampilkan classification report
print(classification_report(y_true, y_pred, target_names=['negative', 'neutral', 'positive']))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns # pastikan Anda sudah mengimpor seaborn

cm = confusion_matrix(y_true, y_pred, labels=['negative', 'neutral', 'positive'])
# Perubahan di sini: 'NEGATIVE', 'NEUTRAL', 'POSITIVE' menjadi 'negative', 'neutral', 'positive'

# Buat visualisasi confusion matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['negative', 'neutral', 'positive'],
            yticklabels=['negative', 'neutral', 'positive'])

plt.title('Confusion Matrix - Sentiment BERT')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.show()

"""# Conclusion"""

# Gabungkan data asli dan hasil prediksi ke dalam satu DataFrame
hasil_klasifikasi = pd.DataFrame({
    'steming_data': data['steming_data'],
    'Sentiment': data['Sentiment'],
    'Predicted_Label': df_bert['label']
})

# Tampilkan 10 baris pertama
hasil_klasifikasi.head(10)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Hitung jumlah kategori di label asli dan prediksi
sentimen_asli = hasil_klasifikasi['Sentiment'].value_counts().sort_index()
prediksi_bert = hasil_klasifikasi['Predicted_Label'].value_counts().sort_index()

# Gabungkan jadi satu DataFrame
perbandingan = pd.DataFrame({
    'Sentimen Aktual': sentimen_asli,
    'Prediksi BERT': prediksi_bert
}).reset_index().rename(columns={'index': 'Sentimen'}).sort_values(by='Sentimen', ascending=False)

# Plot barchart
plt.figure(figsize=(8, 6))
bar = perbandingan.set_index('Sentimen').plot(kind='bar', width=0.7, figsize=(8, 6), color=['#54a0ff', '#ff6b6b'])

plt.title('Perbandingan Jumlah Sentimen \n(Aktual vs Prediksi BERT)', fontsize=14)
plt.ylabel('Jumlah Data')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title='Label')

# Tambahkan label di atas bar
for p in bar.patches:
    bar.annotate(str(p.get_height()), (p.get_x() + p.get_width() / 2, p.get_height()),
                 ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

"""bert berdasarkan score kata, banyak kalimat yang mengarah ke negatif maupun netral tetapi rating tinggi"""

